import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import App from "../src/app/index";
import "../src/app/styles/globals.css"

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NODE_ENV !== "production"
) {
  (async () => {
    const { server } = await import("@/mocks/server");
    server.listen({
      onUnhandledRequest: "bypass",
    });
    console.log("[MSW] Server-side mock enabled");
  })();
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/variable/pretendardvariable.css"
        precedence="default"
      />
      <head>
        <title>블로그</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <App>{children}</App>
      </body>
    </html>
  );
}
